// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/profile-card/ProfileCard.tsx": () => import("../components/mockups/profile-card/ProfileCard.tsx")
};
